FROM node:24-alpine3.21

ENV NODE_VERSION 24.4.1

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src

RUN ls -a
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc \
    npm install && npm install -g nodemon

EXPOSE 4007

CMD ["npm", "run", "dev"]
